from pathlib import Path

BASE_PATH = Path(__file__).parent.parent
USER_WORD_DATA_DIRECTORY_NAME = "user_word_data"
USER_WORD_DATA_PATH = BASE_PATH / USER_WORD_DATA_DIRECTORY_NAME

MAX_MESSAGE_LENGTH = 4096
MAX_MESSAGE_LENGTH_TEST = 30
